---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/CloudDaily/UVyearlyError.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/3629/articles/496627/master/folder/figures/CloudDaily"
    url: "/users/3629/articles/496627/master/file/figures/CloudDaily/UVyearlyError.png"
