---
version: 2
multicolumn: false
web-width: 450px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/contCDMX/contCDMX.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/3629/articles/496627/master/folder/figures/contCDMX"
    url: "/users/3629/articles/496627/master/file/figures/contCDMX/contCDMX.png"
